apiVersion: apps/v1
kind: Deployment
metadata:
  name: vegetable-app
  labels:
    app: web

spec:
  replicas: 3

  selector:
    matchLabels:
      app: web

  template:
    metadata:
      labels:
        app: web

    spec:
      containers:
        - name: veg-container
          image: bhuvana20/veg:v1.0.0
          ports:
            - containerPort: 3000
              envFrom:
                - ConfigMapRef:
                    name: bhuvana-configmap
                  secretRef:
                    name: bhuvana-secret

---
apiVersion: v1
kind: Service
metadata:
  name: veg-service

spec:
  selector:
    app: web

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30008

  type: NodePort