apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: bhuvana-replicaset
  labels:
    app: web

spec: #Define the behaviour of pod
  replicas: 2

  selector:
    matchLabels:
      web: nginx

  template:
    metadata:
      labels:
        web: nginx

    spec: #Define the behaviour of pod
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80